...................................................BATHROOM BUILDING A......................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,59);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,59);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,60);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,60);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,61);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,61);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,62);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,62);


............................................BATHROOM BUILDING B...............................................................


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,63);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,63);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,64);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,64);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,65);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,65);


INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 1, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 2, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 3, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 4, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 5, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('toilet', 6, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 1, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 2, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 3, true,66);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('sink', 4, true,66);


