.................................BUILDING A FIRST FLOOR...................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,1);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,1);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,1);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,1);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,2);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,2);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,2);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,2);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,3);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,3);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,3);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,3);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,4);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,4);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,4);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,4);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,5);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,5);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,5);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,5);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,6);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,6);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,6);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,6);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,7);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,7);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,7);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,7);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,8);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,8);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,8);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,8);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,9);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,9);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,9);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,9);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,10);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,10);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,10);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,10);

..............................................BUILDING A SECOND FLOOR.............................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,11);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,11);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,11);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,11);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,12);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,12);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,12);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,12);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,13);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,13);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,13);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,13);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,14);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,14);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,14);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,14);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,15);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,15);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,15);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,15);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,16);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,16);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,16);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,16);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,17);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,17);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,17);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,17);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,18);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,18);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,18);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,18);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,19);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,19);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,19);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,19);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,20);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,20);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,20);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,20);


.............................................BUILDING B FIRST FLOOR..................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,21);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,21);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,21);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,21);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,22);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,22);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,22);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,22);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,23);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,23);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,23);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,23);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,24);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,24);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,24);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,24);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,25);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,25);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,25);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,25);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,26);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,26);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,26);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,26);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,27);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,27);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,27);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,27);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,28);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,28);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,28);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,28);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,29);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,29);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,29);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,29);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,30);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,30);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,30);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,30);


.................................................BUILDING B SECOND FLOOR..........................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,31);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,31);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,31);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,31);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,32);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,32);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,32);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,32);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,33);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,33);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,33);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,33);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,34);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,34);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,34);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,34);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,35);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,35);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,35);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,35);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,36);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,36);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,36);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,36);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,37);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,37);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,37);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,37);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,38);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,38);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,38);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,38);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,39);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,39);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,39);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,39);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,40);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,40);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,40);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('whiteBoard', 1, true,40);