..........................................................................TUESDAY.......................................................................................................................................

INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT446', '2022-11-08', '446', '12345', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT448', '2022-11-08', '445', '22345', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT440', '2022-11-08', '440', '32345', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT201', '2022-11-08', '441', '42345', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT342', '2022-11-08', '342', '52345', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT110', '2022-11-08', '110', '62345', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'CS140', '2022-11-08', '140', '72345', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT101', '2022-11-08', '101', '82345', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT446', '2022-11-08', '446', '13345', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT448', '2022-11-08', '445', '24345', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT440', '2022-11-08', '440', '35345', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT201', '2022-11-08', '441', '46345', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT342', '2022-11-08', '342', '57345', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT110', '2022-11-08', '110', '68345', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'CS140', '2022-11-08', '140', '92345', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT101', '2022-11-08', '101', '12845', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'MATH150', '2022-11-08', '150', '12345', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'ENG103', '2022-11-08', '103', '22595', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'ISLM101', '2022-11-08', '101', '30845', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'STAT201', '2022-11-08', '201', '42545', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'ISLM104', '2022-11-08', '104', '75942', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT243', '2022-11-08', '243', '95745', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT210', '2022-11-08', '210', '79895', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT244', '2022-11-08', '244', '80465', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'MATH150', '2022-11-08', '150', '17645', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'ENG103', '2022-11-08', '103', '22785', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'ISLM101', '2022-11-08', '101', '38845', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'STAT201', '2022-11-08', '201', '49945', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'ISLM104', '2022-11-08', '104', '50045', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT243', '2022-11-08', '243', '62778', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT210', '2022-11-08', '210', '72975', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT244', '2022-11-08', '244', '82786', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'MATH150', '2022-11-08', '150', '10755', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'ENG103', '2022-11-08', '103', '28645', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'ISLM101', '2022-11-08', '101', '38205', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'STAT201', '2022-11-08', '201', '39505', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'ISLM104', '2022-11-08', '104', '96845', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT243', '2022-11-08', '243', '63680', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT210', '2022-11-08', '210', '70065', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT244', '2022-11-08', '244', '81115', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT446', '2022-11-08', '446', '10075', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT448', '2022-11-08', '445', '20055', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT440', '2022-11-08', '440', '33385', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT201', '2022-11-08', '441', '44901', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT342', '2022-11-08', '342', '46792', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT110', '2022-11-08', '110', '69945', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'CS140', '2022-11-08', '140', '60092', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT101', '2022-11-08', '101', '80934', '8');


.......................................................................WEDNESDAY........................................................................................................................................


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'CS141', '2022-11-09', '141', '94083', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT241', '2022-11-09', '241', '75943', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT242', '2022-11-09', '242', '87395', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'MATH251', '2022-11-09', '251', '84938', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'MGT101', '2022-11-09', '101', '57496', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'ISLM102', '2022-11-09', '102', '57937', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT270', '2022-11-09', '270', '68035', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '16:00:00', '16:50:00', 'IT340', '2022-11-09', '340', '73085', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT230', '2022-11-09', '230', '86947', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT445', '2022-11-09', '445', '74963', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT344', '2022-11-09', '344', '73957', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'E-COM101', '2022-11-09', '101', '58604', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'ISLM103', '2022-11-09', '103', '68947', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT407', '2022-11-09', '407', '58607', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT409', '2022-11-09', '409', '67836', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '17:00:00', '17:50:00', 'IT441', '2022-11-09', '441', '75946', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'CS141', '2022-11-09', '141', '84947', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT241', '2022-11-09', '241', '79576', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT242', '2022-11-09', '242', '93857', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'MATH251', '2022-11-09', '251', '19394', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'MGT101', '2022-11-09', '101', '10047', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'ISLM102', '2022-11-09', '102', '20048', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT270', '2022-11-09', '270', '48759', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '18:00:00', '18:50:00', 'IT340', '2022-11-09', '340', '84086', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT230', '2022-11-09', '230', '93850', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT445', '2022-11-09', '445', '80395', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT344', '2022-11-09', '344', '49508', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'E-COM101', '2022-11-09', '101', '70048', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'ISLM103', '2022-11-09', '103', '30405', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT407', '2022-11-09', '407', '80080', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT409', '2022-11-09', '409', '89370', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '19:00:00', '19:50:00', 'IT441', '2022-11-09', '441', '38084', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'CS141', '2022-11-09', '141', '49085', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT241', '2022-11-09', '241', '49503', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT242', '2022-11-09', '242', '49583', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'MATH251', '2022-11-09', '251', '90303', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'MGT101', '2022-11-09', '101', '47937', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'ISLM102', '2022-11-09', '102', '58376', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT270', '2022-11-09', '270', '39847', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '20:00:00', '20:50:00', 'IT340', '2022-11-09', '340', '49034', '8');


INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT230', '2022-11-09', '230', '40404', '1');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT445', '2022-11-09', '445', '50509', '2');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT344', '2022-11-09', '344', '60940', '3');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'E-COM101', '2022-11-09', '101', '70950', '4');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'ISLM103', '2022-11-09', '103', '90084', '5');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT407', '2022-11-09', '407', '84903', '6');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT409', '2022-11-09', '409', '80883', '7');
INSERT INTO `course` (`course_start_time`, `course_end_time`, `course_name`, `course_date`, `course_number`, `course_crn`, `facility_id`) VALUES ( '21:00:00', '21:50:00', 'IT441', '2022-11-09', '441', '55056', '8');