.....................................................................CLASSROOM BUILDONG A....................................................

INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (101, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (102, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (103, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (104, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (105, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (106, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (107, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (108, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (109, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (110, 'classRoom', 1, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (201, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (202, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (203, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (204, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (205, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (206, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (207, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (208, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (209, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (210, 'classRoom', 2, 20,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (101, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (102, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (103, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (104, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (105, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (106, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (107, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (108, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (109, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (110, 'classRoom', 1, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (201, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (202, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (203, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (204, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (205, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (206, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (207, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (208, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (209, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (210, 'classRoom', 2, 20,true,true,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'lab', 1, 40 ,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'lab', 1, 40 ,true,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'lab', 1, 40 ,true,false,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'lab', 1, 40 ,true,false,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'office', 1, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'office', 1, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (3, 'office', 1, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (4, 'office', 2, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (5, 'office', 2, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (6, 'office', 2, 3 ,false,false,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'office', 1, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'office', 1, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (3, 'office', 1, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (4, 'office', 2, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (5, 'office', 2, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (6, 'office', 2, 3 ,true,true,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'theatre', 2, 100 ,false,true,1);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'theatre', 2, 100 ,true,false,2);
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'bathRoom', 1, 10,true,true,1 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'bathRoom', 1, 10,true,true,1 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (3, 'bathRoom', 2, 10,true,true,1 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (4, 'bathRoom', 2, 10,true,true,1 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'bathRoom', 1, 10,false,false,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (2, 'bathRoom', 1, 10,false,false,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (3, 'bathRoom', 2, 10,false,false,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (4, 'bathRoom', 2, 10,false,false,2 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'storeHouse', 1, 1,true,true,1 );
INSERT INTO facility (facility_number, facility_name, facility_floor, facility_capacity,is_busy,facility_availability, building_number) VALUES (1, 'storeHouse', 1, 1,false,false,2 );