...........................................................OFFICE BUILDING A...........................................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,45);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,45);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,45);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,45);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,45);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,45);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,46);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,46);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,46);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,46);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,46);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,46);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,47);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,47);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,47);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,47);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,47);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,47);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,48);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,48);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,48);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,48);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,48);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,48);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,49);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,49);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,49);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,49);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,49);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,49);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,50);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,50);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,50);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,50);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,50);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,50);


..................................................................OFFICE BUILDING B..............................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,51);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,51);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,51);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,51);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,51);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,51);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,52);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,52);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,52);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,52);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,52);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,52);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,53);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,53);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,53);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,53);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,53);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,53);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,54);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,54);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,54);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,54);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,54);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,54);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,55);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,55);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,55);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,55);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,55);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,55);

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,56);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 1, true,56);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 2, true,56);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('computer', 3, true,56);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 1, true,56);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('printer', 2, true,56);