...........................................................THEATRE BUILDING A..............................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 3, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 4, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 5, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 6, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 7, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 8, true,57);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,57);


.............................................................THEATRE BUILDING B......................................................................................

INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 1, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 2, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 3, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 4, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 5, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 6, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 7, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('airConditioner', 8, true,58);
INSERT INTO utility(utility_name, utility_number, utility_avaliability,facility_id) VALUES ('projector', 1, true,58);