...................................................BATHROOM BUILDING A......................................................................

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 59);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 59);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 60);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 60);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 61);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 61);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 62);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 62);




INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 63);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 63);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 64);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 64);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 65);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 65);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 1, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 2, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 3, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 4, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 5, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('toilet', 6, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 1, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 2, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 3, 66);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('sink', 4, 66);













