.................................BUILDING A FIRST FLOOR...................................................................

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 1);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 1);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 1);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 1);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 2);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 2);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 2);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 2);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 3);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 3);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 3);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 3);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 4);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 4);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 4);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 4);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 5);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 5);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 5);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 5);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 6);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 6);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 6);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 6);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 7);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 7);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 7);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 7);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 8);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 8);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 8);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 8);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 9);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 9);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 9);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 9);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 10);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 10);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 10);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 10);


INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 11);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 11);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 11);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 11);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 12);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 12);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 12);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 12);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 13);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 13);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 13);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 13);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 14);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 14);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 14);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 14);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 15);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 15);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 15);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 15);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 16);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 16);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 16);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 16);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 17);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 17);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 17);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 17);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 18);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 18);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 18);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 18);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 19);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 19);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 19);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 19);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 20);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 20);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 20);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 20);



INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 21);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 21);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 21);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 21);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 22);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 22);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 22);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 22);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 23);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 23);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 23);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 23);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 24);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 24);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 24);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 24);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 25);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 25);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 25);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 25);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 26);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 26);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 26);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 26);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 27);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 27);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 27);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 27);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 28);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 28);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 28);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 28);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 29);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 29);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 29);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 29);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 30);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 30);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 30);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 30);



INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 31);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 31);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 31);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 31);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 32);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 32);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 32);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 32);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 33);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 33);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 33);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 33);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 34);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 34);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 34);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 34);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 35);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 35);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 35);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 35);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 36);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 36);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 36);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 36);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 37);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 37);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 37);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 37);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 38);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 38);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 38);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 38);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 39);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 39);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 39);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 39);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 40);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 40);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 40);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('whiteBoard', 1, 40);