...........................................................OFFICE BUILDING A...........................................................................................

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 45);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 45);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 45);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 45);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 45);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 45);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 46);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 46);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 46);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 46);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 46);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 46);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 47);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 47);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 47);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 47);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 47);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 47);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 48);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 48);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 48);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 48);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 48);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 48);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 49);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 49);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 49);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 49);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 49);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 49);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 50);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 50);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 50);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 50);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 50);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 50);



INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 51);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 51);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 51);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 51);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 51);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 51);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 52);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 52);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 52);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 52);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 52);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 52);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 53);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 53);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 53);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 53);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 53);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 53);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 54);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 54);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 54);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 54);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 54);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 54);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 55);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 55);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 55);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 55);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 55);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 55);

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 56);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 1, 56);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 2, 56);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('computer', 3, 56);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 1, 56);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('printer', 2, 56);