...........................................................THEATRE BUILDING A..............................................................................

INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 3, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 4, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 5, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 6, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 7, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 8, 57);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 57);



INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 1, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 2, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 3, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 4, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 5, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 6, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 7, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('airConditioner', 8, 58);
INSERT INTO utility(utility_name, utility_number, facility_id) VALUES ('projector', 1, 58);